Repository hyoni-ch/fan-site, pull requests merged in 2025-03, with the labels that each got.

#3 env: mui 설치 및 theme 적용
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/theme.ts
Labels: env

#5 헤더 네브바 기능 구현
  public/images/jjoul.png
  public/images/zoulsign.png
  src/app/(route)/cart/page.tsx
  src/app/(route)/mypage/page.tsx
  src/app/layout.tsx
  src/components/headerNav.tsx
  src/styles/headerStyles.ts
  src/utils/scrollUtils.ts
Labels: feat, design

#10 로그인 전역 상태 관리 및 컴포넌트 UI 개발
  package-lock.json
  package.json
  public/images/zoulsign.png
  src/api/auth.ts
  src/app/(route)/cart/page.tsx
  src/app/(route)/join/page.tsx
  src/app/(route)/login/_components/LoginForm.tsx
  src/app/(route)/login/_components/RegisterForm.tsx
  src/app/(route)/login/page.tsx
  src/app/page.tsx
  src/components/headerNav.tsx
  src/store/authStore.ts
  src/utils/api.ts
  src/utils/auth.ts
  src/utils/token.ts
Labels: feat, env, design

#12 이메일 인증 & 로그인 UI 컴포넌트 추가 개발
  .gitignore
  src/api/auth.ts
  src/app/(route)/cart/page.tsx
  src/app/(route)/login/page.tsx
  src/app/(route)/verifyemail/page.tsx
  src/components/headerNav.tsx
  src/constants/apiUrl.ts
  src/utils/api.ts
Labels: feat, env

#20 메인페이지 섹션 및 마이페이지 스타일 수정
  src/app/(route)/mypage/page.tsx
  src/app/layout.tsx
  src/components/mainSection.tsx
Labels: design

#21 Feat/#18 굿즈 메인페이지 개발
  src/app/(route)/goods/page.tsx
  src/components/mainGoods.tsx
  src/components/mainSlider.tsx
  src/styles/theme.ts
Labels: feat, env, design

#23 다이어리 페이지 모든 기능 구현 + 리팩토링 필수
  next.config.ts
  package-lock.json
  package.json
  public/images/diary1.png
  src/api/diaryDetail.ts
  src/api/getLatestDiary.ts
  src/app/(route)/diary/[id]/page.tsx
  src/app/(route)/diary/everydiary/page.tsx
  src/app/(route)/diary/page.tsx
  src/app/(route)/verifyemail/page.tsx
  src/components/diaryPage/diaryImage.tsx
  src/components/diaryPage/diaryImageContent.tsx
  src/components/diaryPage/gridContainer.tsx
  src/components/diaryPage/hoverOverlay.tsx
  src/hooks/useFetchArticle.ts
  src/hooks/useLikeHandler.ts
  src/store/commentStore.ts
  src/store/diaryLikeStore.ts
  src/store/diaryStore.ts
  src/styles/diaryDetailStyles.ts
  src/types/diaryMain.ts
  src/utils/formatTimeToKST.ts
Labels: feat, env, design

#26 feat: comment& replyComments delete feature
  src/api/auth.ts
  src/app/(route)/diary/[id]/page.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/store/authStore.ts
Labels: feat

#28 Feat/#6 장바구니 페이지 개발
  src/app/(route)/cart/page.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
  src/components/mainGoods.tsx
  src/store/cartStore.ts
Labels: feat, design

#29 프로필 페이지 컴포넌트 기능 개발
  package-lock.json
  package.json
  public/images/jjoul.png
  public/images/profile2.png
  src/api/profile.ts
  src/app/(route)/artist/(artistProfile)/profileHeader.tsx
  src/app/(route)/artist/(artistProfile)/profileInfo.tsx
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/artist/(tabs)/awardsTab.tsx
  src/app/(route)/artist/(tabs)/concertTabs.tsx
  src/app/(route)/artist/(tabs)/dramasTab.tsx
  src/app/(route)/artist/(tabs)/profileTabs.tsx
  src/app/(route)/artist/page.tsx
  src/app/(route)/login/page.tsx
  src/app/layout.tsx
  src/app/subLayout.tsx
  src/components/headerNav.tsx
  src/styles/headerStyles.ts
  src/types/iprofile.ts
Labels: feat, design
