Repository hyoni-ch/fan-site, pull requests merged in 2025-04, with the labels that each got.

#31 discography component UI & featuring
  next.config.ts
  src/api/discography.ts
  src/app/(route)/discography/_components/albumDetail.tsx
  src/app/(route)/discography/_components/albumLists.tsx
  src/app/(route)/discography/page.tsx
  src/app/(route)/mypage/page.tsx
  src/components/headerNav.tsx
  src/types/mockAlbumList.ts
  src/utils/youtube.ts
Labels: feat, env, design

#34 Design/#17 푸터 수정
  public/images/icon/facebookIcon.png
  public/images/icon/instagramIcon.png
  public/images/icon/spotifyIcon.png
  public/images/icon/tiktokIcon.png
  public/images/icon/xIcon.png
  public/images/icon/youtubeIcon.png
  src/components/footer.tsx
Labels: design

#35 굿즈디테일 및 장바구니 페이지 버튼 기능 수정
  src/app/(route)/cart/page.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
Labels: feat

#36 마이페이지 디자인 수정 및 mui 적용
  src/app/(route)/mypage/page.tsx
  src/components/mainSlider.tsx
Labels: design

#37 메인페이지 버튼 링크 추가 및 굿즈 섹션 수정
  src/app/page.tsx
  src/components/mainGoods.tsx
Labels: feat, design

#41 굿즈 디테일 페이지 디자인 수정
  src/app/(route)/goods/_components/goodsDetail.tsx
Labels: design

#54 마이페이지 디자인 수정 및 로그아웃 버튼 추가
  src/app/(route)/mypage/page.tsx
Labels: feat, design

#55 Feat/#44 굿즈 Create 개발
  src/api/auth.ts
  src/api/goods.ts
  src/app/(route)/goods/_components/goodsCreate.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/app/(route)/goods/create/page.tsx
  src/store/authStore.ts
Labels: feat

#58 마이페이지 로그아웃 요청 수정
  src/app/(route)/mypage/page.tsx
Labels: refac

#60 마이페이지 로그인한 회원 정보 get 요청 추가 및 수정
  src/api/auth.ts
  src/app/(route)/mypage/page.tsx
Labels: feat

#62 전체 이미지 src 프록시 설정
  package-lock.json
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/artist/(tabs)/concertTabs.tsx
  src/app/(route)/artist/(tabs)/dramasTab.tsx
  src/app/(route)/diary/[id]/page.tsx
  src/app/(route)/diary/page.tsx
  src/app/(route)/discography/_components/albumDetail.tsx
  src/app/(route)/discography/_components/albumLists.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/components/mainGoods.tsx
  src/components/mainSlider.tsx
Labels: env

#64 이메일 인증 함수 배포 url 미인증 사태 해결 & 다이어리 전체 보기 페이지 로딩 상태 추가
  src/api/auth.ts
  src/app/(route)/diary/everydiary/page.tsx
  src/app/(route)/verifyemail/_components/verifyEmailServer.tsx
  src/store/diaryStore.ts
Labels: fix, feat

#66 권한 부여 API 연동 및 선택 박스 UI 수정
  src/api/admin.ts
  src/api/auth.ts
  src/app/(route)/admin/_component/roleSelect.tsx
  src/app/(route)/admin/_component/userListTable.tsx
  src/app/(route)/admin/page.tsx
Labels: feat, design

#68 다이어리 글쓰기 컴포넌트
  src/api/diary/diaryDetail.ts
  src/api/diary/diaryWrite.ts
  src/api/diary/getLatestDiary.ts
  src/app/(route)/diary/[id]/page.tsx
  src/app/(route)/diary/everydiary/page.tsx
  src/app/(route)/diary/page.tsx
  src/app/(route)/diary/write/_components/DiaryForm.tsx
  src/app/(route)/diary/write/_components/DiaryImageList.tsx
  src/app/(route)/diary/write/_components/DiaryStyles.ts
  src/app/(route)/diary/write/_components/DiarySubmitButton.tsx
  src/app/(route)/diary/write/_components/DiaryTextFields.tsx
  src/app/(route)/diary/write/page.tsx
  src/hooks/useFetchArticle.ts
  src/hooks/useLikeHandler.ts
Labels: feat, design

#71 refac: 앨범 페이지 탭 UI 수정 및 api 연동
  next.config.ts
  src/api/discography.ts
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/artist/(tabs)/concertTabs.tsx
  src/app/(route)/artist/(tabs)/dramasTab.tsx
  src/types/iprofile.ts
Labels: refac

#73 앨범 페이지 UI 수정 및 리프레시 토큰 바디 설정
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/discography/_components/albumDetail.tsx
  src/app/(route)/discography/_components/albumLists.tsx
  src/app/(route)/discography/page.tsx
  src/utils/api.ts
Labels: fix, design, refac

#79 refac: 마이페이지 zustand 로그인 상태 수정
  src/app/(route)/mypage/page.tsx
  src/store/authStore.ts
Labels: fix, refac

#80 design: 헤더 햄버거 메뉴바 수정
  src/components/headerNav.tsx
Labels: design

#83 fix: 굿즈 상품 추가 및 수정 api 에러
  src/api/goods.ts
  src/app/(route)/admin/_component/goodsManager.tsx
Labels: fix

#86 굿즈 추가 컴포넌트 빌드 오류 수정
  src/app/(route)/goods/_components/goodsCreate.tsx
Labels: fix

#88 굿즈 업데이트 컴포넌트 빌드 오류 수정
  src/app/(route)/goods/_components/goodsUpdate.tsx
Labels: fix

#91 굿즈 수정, 삭제 api 경로 수정
  src/api/goods.ts
Labels: fix

#93 Refac/#92 타입 리팩토링 및 부분 디자인 수정
  src/app/(route)/admin/_component/goodsManager.tsx
  src/app/(route)/admin/_component/goodsModal.tsx
  src/app/(route)/cart/page.tsx
  src/app/(route)/goods/[id]/update/page.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/app/(route)/goods/_components/goodsUpdate.tsx
  src/app/(route)/mypage/page.tsx
  src/components/mainPage/mainGoods.tsx
  src/components/mainPage/mainSlider.tsx
  src/styles/slideStyles.css
  src/types/igoods.ts
Labels: feat, design, refac

#97 이미지 경로 수정 및 S3 버킷 url 상수화
  next.config.ts
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/artist/(tabs)/dramasTab.tsx
  src/app/(route)/diary/[id]/page.tsx
  src/app/(route)/diary/everydiary/page.tsx
  src/app/(route)/diary/page.tsx
  src/app/(route)/discography/_components/albumDetail.tsx
  src/app/(route)/discography/_components/albumLists.tsx
  src/app/(route)/goods/_components/goodsDetail.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/components/mainPage/mainGoods.tsx
  src/components/mainPage/mainSlider.tsx
  src/constants/s3Image.ts
  src/hooks/useProfileTabApi/useFetchProfileData.ts
Labels: refac

#107 헤더 장바구니 수량 표시 및 장바구니 페이지 이미지 크기 수정
  src/app/(route)/cart/page.tsx
  src/components/headerNav.tsx
Labels: feat, design

#111 로그인 관련 api + 리프레시 토큰 + 프로필 탭 기능 확장
  src/api/auth.ts
  src/app/(route)/admin/page.tsx
  src/app/(route)/artist/(artistProfile)/profileHeader.tsx
  src/app/(route)/artist/(artistProfile)/profileInfo.tsx
  src/app/(route)/artist/(tabSkeleton)/AlbumSkeleton.tsx
  src/app/(route)/artist/(tabSkeleton)/ConcertSkeleton.tsx
  src/app/(route)/artist/(tabSkeleton)/DramaSkeleton.tsx
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/artist/(tabs)/concertTabs.tsx
  src/app/(route)/artist/(tabs)/dramasTab.tsx
  src/app/(route)/artist/(tabs)/profileTabs.tsx
  src/app/(route)/artist/page.tsx
  src/app/lib/react-query/prefetchAlbums.ts
  src/app/lib/react-query/prefetchProfileTabData.ts
  src/app/lib/react-query/prefetchProfileTabs.ts
  src/app/provider.tsx
  src/components/LoadingIndicator.tsx
  src/components/commonProfileTab/refetchButton.tsx
  src/hooks/useProfileTabApi/useFetchAlbum.ts
  src/hooks/useProfileTabApi/useFetchConcerts.ts
  src/hooks/useProfileTabApi/useFetchDramas.ts
  src/hooks/useProfileTabApi/useFetchProfileData.ts
  src/hooks/useProfileTabApi/useProfileTabData.ts
  src/store/albumStore.ts
  src/store/authStore.ts
  src/store/profile/albumStore.ts
  src/store/profile/concertStore.ts
  src/store/profile/dramaStore.ts
  src/types/iProfileState.ts
  src/utils/api.ts
  src/utils/authUtils.ts
Labels: feat, refac

#114 관리자 페이지 관련 개발 및 수정
  src/api/discography.ts
  src/app/(route)/admin/_component/formModal.tsx
  src/app/(route)/admin/_component/goodsManager.tsx
  src/app/(route)/admin/_component/goodsModal.tsx
  src/app/(route)/admin/_component/manager/discography.tsx
  src/app/(route)/admin/_component/manager/goods.tsx
  src/app/(route)/admin/_component/manager/user.tsx
  src/app/(route)/admin/_component/managerTable.tsx
  src/app/(route)/admin/_component/trackAddFormModal.tsx
  src/app/(route)/admin/_component/userListTable.tsx
  src/app/(route)/admin/page.tsx
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/(route)/discography/page.tsx
  src/app/(route)/goods/_components/goodsList.tsx
  src/components/mainPage/mainSlider.tsx
  src/components/pagination.tsx
Labels: feat, design, refac

#117 fix: 빌드 에러 해결
  next.config.ts
  src/api/discography.ts
  src/app/(route)/admin/_component/manager/discography.tsx
  src/app/(route)/artist/(tabs)/albumTab.tsx
  src/app/lib/react-query/prefetchProfileTabs.ts
  src/store/authStore.ts
  src/types/iprofile.ts
Labels: fix
